### ISSUE TITLE
【Guard of Wuthering Snow 2-Pc：Reducing DMG taken by 8%】is ignored when calculating EHP（Effective HP）

### ISSUE THREAD

**Issue by dongchengjie** [fribbels/hsr-optimizer#1]
This causes 【Guard of Wuthering Snow】 to look less "tough" than other Sets.

**Comment by fribbels** [comment]
Will address this in the coming update with better damage calculations!

**Comment by fribbels** [comment]
The update is live and EHP calculations are updated with the wuthering snow set now
