### ISSUE TITLE
[Feature] Suggestions for filters and interaction

### ISSUE THREAD

**Issue by dongchengjie** [fribbels/hsr-optimizer#165]
1. Remove rating filter **CV** which is no longer in use, and swap the order of **EHP** and **WEIGHT**(the order they are displayed in Rating filters).<img width="1221" alt="cv" src="https://github.com/fribbels/hsr-optimizer/assets/37543964/d5bd7a1f-d650-4f5f-86d1-484b9272c67b">
2. Since there is no stat filter **HEAL**,why not change it into a rating filter **HEALING VALUE**(healing provided in combat) instead.
3. It would be better if could be reminded which character you are goting to  operate.
<img width="763" alt="deletepng" src="https://github.com/fribbels/hsr-optimizer/assets/37543964/2456264a-c998-43d0-a217-72c99414a9e0">

**Comment by fribbels** [comment]
@dongchengjie thanks for the suggestions! I've added 1 and 3, 2 will have to be a larger project https://github.com/fribbels/hsr-optimizer/issues/175

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/204
