### ISSUE TITLE
[Bug] Fix substat ordering on relic filters

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#181]
<< Reserved for first task >>

Motivation: Currently on the relics tab page, the substat order doesnt really match the main stat order. For example Break Effect comes before HP% for some reason.

![Image](https://github.com/fribbels/hsr-optimizer/assets/7908525/d704ae8a-2b08-4d25-a7e6-0d3eb533d7cd)

Goal: Re-order the stats for consistency, make sure the subs match the main stat order. Some substats dont appear as main so lets go with RES last.

The code where this filter is generated is here: https://github.com/fribbels/hsr-optimizer/blob/main/src/components/RelicFilterBar.jsx#L103

**Comment by fribbels** [comment]
In progress @Kodie

**Comment by fribbels** [comment]
Double check on the main stat ordering as well for consistency

**Comment by KodieCalcs** [comment]
Requested fix, PR #196

**Comment by KodieCalcs** [comment]
Would be closed by PR #196

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/204
