### ISSUE TITLE
[Bug] E3 and E5 trace increases are incorrect on most characters

### ISSUE THREAD

**Issue by pikcelery** [fribbels/hsr-optimizer#193]
# Issue Template

## Description
Characters in HSR have eidolons at E3 and E5 that gives boosts to their traces. The specific assignment varies from character to character, for example:
* Argenti's E3 boosts Skill and Talent and his E5 boosts Ultimate and Basic
* Arlan's E3 boosts Skill and Basic and his E5 boosts Ultimate and Talent

In the optimizer's code ([utils.ts](https://github.com/fribbels/hsr-optimizer/blob/main/src/lib/conditionals/utils.ts)), characters are coded to either have E3 Skill/Talent and E5 Ultimate/Basic or the reverse (E3 Ultimate/Basic and E5 Skill/Talent), but this doesn't match up with how the eidolons are written in the game.

To help with fixing the issue, I've compiled a table below that shows the eidolon assignments for all characters currently in the game.

Legend:
* Eidolon 3A - First boosted trace at Eidolon 3
* Eidolon 3B - Second boosted trace at Eidolon 3
* Eidolon 5A - First boosted trace at Eidolon 5
* Eidolon 5B - Second boosted trace at Eidolon 5
* Fribbels Basic - The function that should be used to represent the character's basic attack
* Fribbels Skill - The function that should be used to represent the character's skill
* Fribbels Ult- The function that should be used to represent the character's ult
* Fribbels Talent- The function that should be used to represent the character's basic talent
* Valid - Whether the character's E3/E5 are correctly implemented in the optimizer

|  | Eidolon 3A | Eidolon 3B | Eidolon 5A | Eidolon 5B | Fribbels Basic | Fribbels Skill | Fribbels Ult | Fribbels Talent | Valid |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Argenti | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | TRUE |
| Arlan | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Asta | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | TRUE |
| Bailu | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | TRUE |
| Black Swan | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | TRUE |
| Blade | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Bronya | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Clara | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Dan Heng | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Dr. Ratio | Ultimate | Basic | Skill | Talent | basicRev | skillRev | ultRev | talentRev | FALSE |
| Fu Xuan | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | FALSE |
| Gepard | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Guinaifen | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Hanya | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Herta | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Himeko | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Hook | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Huohuo | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Imbibitor Lunae | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Jing Yuan | Ultimate | Basic | Skill | Talent | basicRev | skillRev | ultRev | talentRev | FALSE |
| Jingliu | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Kafka | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Luka | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | FALSE |
| Luocha | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Lynx | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| March 7th | Ultimate | Basic | Skill | Talent | basicRev | skillRev | ultRev | talentRev | FALSE |
| Misha | Ultimate | Basic | Skill | Talent | basicRev | skillRev | ultRev | talentRev | TRUE |
| Natasha | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Pela | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Qingque | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Ruan Mei | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Sampo | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Seele | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | FALSE |
| Serval | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Silver Wolf | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | FALSE |
| Sparkle | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Sushang | Ultimate | Talent | Skill | Basic | basic | skillRev | ultRev | talent | FALSE |
| Tingyun | Ultimate | Basic | Skill | Talent | basicRev | skillRev | ultRev | talentRev | FALSE |
| Topaz & Numby | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Trailblazer (Destruction) | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | FALSE |
| Trailblazer (Preservation) | Skill | Talent | Ultimate | Basic | basic | skill | ult | talent | FALSE |
| Welt | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Xueyi | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Yanqing | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |
| Yukong | Skill | Basic | Ultimate | Talent | basicRev | skill | ult | talentRev | FALSE |

## Steps to Reproduce
Below is an example of the issue (how I discovered the problem while using the optimizer)

* Set character to Clara, with E2
![Screenshot 2024-03-09 011121](https://github.com/fribbels/hsr-optimizer/assets/162790805/8daf66a9-95aa-4218-ad5f-fc3a4efd11e0)

* Click Start Optimizer

* Note FUA value
![Screenshot 2024-03-09 011510](https://github.com/fribbels/hsr-optimizer/assets/162790805/fb1b8568-651e-491f-ac3f-98bd839531f3)
* Set Clara to E3
![Screenshot 2024-03-09 011716](https://github.com/fribbels/hsr-optimizer/assets/162790805/da9e5664-764a-4b41-a744-61abd8f4b10e)

* Click Start Optimizer
* FUA value has changed, despite Clara's E3 only increasing her skill damage
![Screenshot 2024-03-09 011604](https://github.com/fribbels/hsr-optimizer/assets/162790805/e67c63d2-7e32-4111-9c7f-c6bed7d15e14)
> Skill Lv. +2, up to a maximum of Lv. 15. Basic ATK Lv. +1. up to a maximum of Lv. 10.

**Comment by fribbels** [comment]
@pikcelery thanks so much for the table, that helps a lot. I'll work on this tomorrow for the next beta to main update

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/204
