### ISSUE TITLE
Feature: Make main stat non-editable on the relic editing modal

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#21]
Currently both the enhance (e.g. +12) and main stat are editable

Goal: Level and grade should be enough to calculate the main stat so users shouldn't be able to edit main stats directly.

Other manual relic entry improvements are welcome too -> Auto setting main stat on Hands / Head piece for example

**Comment by ronaldpereira** [comment]
this should help as a reference as well for main stats increments calculations:

![Image](https://github.com/fribbels/hsr-optimizer/assets/12674637/17545986-3dbd-41e1-a9f1-f91f19663702)

**Comment by ronaldpereira** [comment]
I also have for substats rolls if we want to create a increment selector in the future:

![Image](https://github.com/fribbels/hsr-optimizer/assets/12674637/76eebb39-40e8-49df-9d96-1f938118bce0)
