### ISSUE TITLE
[Feature] Show roll quality (%) on relics

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#23]
### Motivation

Currently, relics can roll low / mid / high but the optimizer doesn't show them

### Objective

Display roll quality as 80%/90%/100% and a sum of roll quality per relic. Possibly show these numbers when the relic is hovered

**Comment by ronaldpereira** [comment]
These are the substats rolls we can use for reference:

![image](https://github.com/fribbels/hsr-optimizer/assets/12674637/117b412d-2ac1-4474-b852-d44145e41399)

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/236
