### ISSUE TITLE
[Feature] Add support for importing relics from HoyoLAB Battle Records

### ISSUE THREAD

**Issue by agalq13** [fribbels/hsr-optimizer#241]
freesr-tools.pages.dev uses json data from HoyoLAB to import relics.

https://github.com/fribbels/hsr-optimizer/assets/71724834/ea27c71d-3bfc-4d60-8014-cc0f0da7e17f

It's a good method because it allows to scan every single character, not just 8.
And it doesn't require downloading anything.

**Comment by fribbels** [comment]
Oh cool, I didn't know about this site - thanks for the info!

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/408
