### ISSUE TITLE
[Feature] Disable messenger set in teammate sync

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#244]
### Motivation

![image](https://github.com/fribbels/hsr-optimizer/assets/7908525/8b262ddd-dc66-4dec-aca8-16de8196ed30)

Currently teammate imports with Messenger activate the 12% SPD buff by default, but this can be misleading if users arent checking carefully since the SPD buff is inconsistent

### Objective

Default the messenger set to not show up on teammate select when teammates have messenger set. This should also not show up when the user clicks the Sync button between the teammate name / eidolon

Starting point: https://github.com/fribbels/hsr-optimizer/blob/6006e59d302b1577d90c745d66e5e23a8b79fce6/src/components/optimizerTab/optimizerForm/TeammateCard.tsx#L146

**Comment by milo-sc** [comment]
working on this

**Comment by fribbels** [comment]
Deployed in https://github.com/fribbels/hsr-optimizer/pull/370
