### ISSUE TITLE
[Feature] Default the loaded character on new sessions to the last selected character

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#275]
### Motivation

Currently the optimizer defaults to the priority #1 character but often that isnt the character people use the most. 

### Objective

QOL: Save a new save-file state with the last selected optimizer character, and load that by default instead of the priority 1 character

**Comment by khisaki** [comment]
I'll pick this up

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/298
