### ISSUE TITLE
[Feature] Add a button to reset scoring algorithms for all characters

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#278]
*** Motivation

Currently the only way to undo scoring changes is to revert characters one by one. But its not always clear which characters have been changed.

### Objective

* Add a new button on the Scoring Algorithm modal to the right of "Reset to default", called "Reset all characters"
<img width="912" alt="image" src="https://github.com/fribbels/hsr-optimizer/assets/7908525/0b8d23a2-6a4e-427a-80dc-1b613e103dc1">
* This button should be a Red danger button from antd
* The button should have a popover confirmation: "Are you sure you want to reset the scoring algorithm for all characters?" Yes/No

**Comment by kaixin-hc** [comment]
hi! wld like to give this a try

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/298
