### ISSUE TITLE
[Bug] Character Optimizer Substat Weights Don't Save

### ISSUE THREAD

**Issue by WolfBungalow** [fribbels/hsr-optimizer#331]
## Description
On the Character Optimizer page, the values entered for the "Substat weight filter" and "Top % of weighted relics" are no longer saved and reset to defaults.

## Steps to Reproduce

1. Enter a character optimizer page.
2. Change the "Substat weight filter" or "Top % of weighted relics" values.
3. Click "Start optimizer", click "Cancel".
4. Enter a different character optimizer page.
5. Return to original character optimizer page. The values will reset.

## Expected Behavior
The set values used to save.

## Actual Behavior
The values are reset.

## Screenshots
![image](https://github.com/fribbels/hsr-optimizer/assets/25573424/a4fde6d2-0fc6-41be-9d15-8f1a59b88d5d)

## Additional Information
This issue started with commit 2f5d890. Commit b09d6ea works as expected.

**Comment by fribbels** [comment]
Thanks for the bug report! Deploying the fix in like 30 mins or so
