### ISSUE TITLE
[Feature] Allow multiple weight profiles for each character

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#35]
### Motivation

Currently we have one weight profile per character - which can be edited but the scoring weights don't fully work for every build/playstyle: for example crit vs dot kafka / crit vs support silverwolf

### Objective

How to actually do this is pretty open ended and have pros and cons, but some options to discuss:

* Make the scoring conditional: if CV > 50 then use crit scoring profile, else use dot profile
* Allow users to select a weight profile from the characters menu or the scoring modal. So you could have SW (support) or SW (DPS) 

Note: This work is related to the leaderboards project

**Comment by fribbels** [comment]
Deprioritizing this now that we have sim scores

**Comment by FI00ds** [comment]
Looking at this mainly in the context of having 1 profile for super break and 1 profile for crit (e.g. Himeko, Hunt March 7th), how much would we want to be included in the profiles?

Weights was mentioned but I feel that valid mainstats would also make sense to add. Mostly just questioning if it makes sense to also include all the optimizer options in the profile (selected relic sets, lc, combo, etc...)

**Comment by fribbels** [comment]
Resolving - I think we're leaning towards one default weight per character and allowing the user to customize. Additional complexity not worth it.
