### ISSUE TITLE
The character page its missing the energy regen stat 

### ISSUE THREAD

**Issue by duradara** [fribbels/hsr-optimizer#356]
## Description
Like the title says the character page its missing the energy regen stat

## Screenshots
![Screenshot 2024-05-17 164710](https://github.com/fribbels/hsr-optimizer/assets/50158352/e232227d-2fb8-45ed-9767-6376f532f250)

**Comment by fribbels** [comment]
This was partially a space-saving thing since Energy regen and Healing boost aren't substats

I'll try to add them back in when we have more UI space
