### ISSUE TITLE
[Feature] Allow for users to choose whether they want to use the DPS scoring or old scoring systems.

### ISSUE THREAD

**Issue by solarProtag** [fribbels/hsr-optimizer#376]
Myself and others who have used the HSR Optimizer for a while now agree that while the new DPS scoring system is interesting, we would like the option to use the old scoring system as well, as many of our builds have suddenly become ranked much lower than they were previously.

**Comment by fribbels** [comment]
Yeah I think its fair to give users the option, hotfix deployed

**Comment by solarProtag** [comment]
Thank you very much!
