### ISSUE TITLE
[bug] Improve multi-Trailblazer support from reliquary-archiver

### ISSUE THREAD

**Issue by FaeronGaming** [fribbels/hsr-optimizer#416]
# Issue Template

## Description
reliquary-archiver generates character json for each of the trailblazer's paths with mixed results. When importing both characters and relics this can work fine while others it is a grab-bag of issues including incorrect LC assignments, missing builds from other paths or even relics not assigning to the correct build.

## Steps to Reproduce

1. Generate reliquary archive json
2. Import relics and characters from generated archive

## Expected Behavior

* Each trailblazer path available to the player has a build present in the characters tab
* Each build is correctly named for the selected gender and path
* Each build as the correct light cone equipped
* Each build has the correct relics equipped

## Actual Behavior

* In the current state (at the time of this post) Harmony trailblazer is treated as Stelle (Destruction)
  * this is due to IceDynamix/reliquary-archiver#16 and will be fixed in an upcoming release
* Due to the above Stelle (Destruction)'s relics will be replaced by Stelle (Harmony)'s
* Relics do not neccesarily match the build used in-game
  * this is due to IceDynamix/reliquary-archiver#12. A fix for this is in progress
* The equipped LC is the same across builds regardless of path\
  * same issue as above

### Current State
![image](https://github.com/fribbels/hsr-optimizer/assets/3262183/72abd644-1dd6-42e3-ad73-c489f6a0f4ff)
![image](https://github.com/fribbels/hsr-optimizer/assets/3262183/65d7171f-1e25-4ef1-867b-f4d0ad457f86)
![image](https://github.com/fribbels/hsr-optimizer/assets/3262183/bfb3fc0f-7219-400e-bc8c-f999908854f1)

### In upcoming update
![image](https://github.com/fribbels/hsr-optimizer/assets/3262183/26a749af-642c-42c9-9792-a7bc01d8b155)
![image](https://github.com/fribbels/hsr-optimizer/assets/3262183/67ca3a2d-935c-428d-a382-0d8f29680977)
![image](https://github.com/fribbels/hsr-optimizer/assets/3262183/176732b8-6f39-4aeb-b459-6293aa345fa0)

**Comment by fribbels** [comment]
Hey! Thanks for the heads up - just to clarify, do these issues get fixed if the new reliquary patch goes out with the correct trailblazer path / name?

**Comment by FaeronGaming** [comment]
That is correct. The issue with HMC getting imported as Stelle (Destruction) is already in dev and will get fixed as soon as a release is made. Everything else will be fixed with IceDynamix/reliquary-archiver#28 is merged, and I can't imagine a new release being cut without it.

Also, I'll have a PR up for this issue soon. My prettier kicked in and changed a bunch of stuff unnecessarily so I'm getting that fixed up atm

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/442
