### ISSUE TITLE
hardcoded data in funtion getOverrideTraces seems to be wrong

### ISSUE THREAD

**Issue by dongchengjie** [fribbels/hsr-optimizer#42]
When I was calculating today,I found the [Effect RES] value of Set that I had equipped became lower in the result table.
<img width="1091" alt="pic" src="https://github.com/fribbels/hsr-optimizer/assets/37543964/9ef171e1-1eeb-4002-ad00-3a2a5f5288e1">

Then I debugged the code and found that the hardcoded data was inaccurately defined in the function **getOverrideTraces**.

So I rechecked the data:
I just can't understand why you multiply RES by 2/3, but not all characters do that.

Luocha
[Constants.Stats.ATK_P]: 0.3,	=should be=》	[Constants.Stats.ATK_P]: 0.28,

March 7th、Himeko、Welt、Serval、Sampo、Bailu
[Constants.Stats.RES]: 0.067,	=should be=》	[Constants.Stats.RES]: 0.10,

Gepard\Natasha
[Constants.Stats.RES]: 0.12,	=should be=》	[Constants.Stats.RES]: 0.18,

**Comment by fribbels** [comment]
Thank you for the find! I will check on these tonight. Can't wait to get to this task so we can get rid of the hardcoded values https://github.com/fribbels/hsr-optimizer/issues/31

**Comment by fribbels** [comment]
Hotfix deployed, thanks again!
