### ISSUE TITLE
[Bug] Relic insights panel shows impossible upgraded stats

### ISSUE THREAD

**Issue by FI00ds** [fribbels/hsr-optimizer#433]
## Description

When hovering over a character in the relic insights panel, impossible upgraded substats are displayed

## Steps to Reproduce

1. Select a relic with 4 substat lines
2. Hover over character in relic insights panel with 1 or more of their max weight substats not present on relic

## Expected Behavior

Expect to only see substats present on the relic once the relic has 4 lines
## Actual Behavior

Substats that are not present on the relic appear as "upgraded stats"
## Screenshots

![image](https://github.com/fribbels/hsr-optimizer/assets/122728302/95866d07-093a-4b70-9ef9-dfe130925c98)

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/442
