### ISSUE TITLE
[Tech debt] Typescript migration

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#44]
Now's a good time to start migrating to TS for maintainability - creating a tech debt task to track. 

The vite migration has completed, now we're migrating typescript files piecemeal

**Comment by Garfield550** [comment]
Want to help complete this task.

**Comment by fribbels** [comment]
@Garfield550 Hi, would love some help on this! We're working on converting the js into ts in a gradual migration instead of all at once, so I've been going at it one file at a time. Come drop by the discord server #dev-chat to coordinate and I can respond faster there.

**Comment by Garfield550** [comment]
@fribbels,
Sorry for the late reply, I'm already on Discord with the same name. Due to work arrangements, I may not be able to start working on this issue until next week.

**Comment by fribbels** [comment]
Oh sure, no worries. I'm doing the migration as a long term thing so take your time

**Comment by fribbels** [comment]
Going to call this one done, reviewed the remaining files and they're due for a rewrite rather than a migration. Everything else has been migrated. Further typescript improvements will be added as part of regular development.

![Image](https://github.com/user-attachments/assets/1b4357c7-5282-4cfd-9756-c44595ec67ec)
