### ISSUE TITLE
[Feature] Have an option to replace substat scoring with potential 

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#440]
### Motivation

The current substat scoring doens't consider the context of the maximum potential of the relic so the can be cases where its not accurate for custom relics.

### Goal

Enable an option to switch between the two scoring mechanisms

**Comment by zhenduow** [comment]
Hi,

This looks great! It is much more preferable than the current scoring system. Is it going to happen?

**Comment by fribbels** [comment]
I probably won't be able to work on it for at least a couple months unless one of the contributors takes it up, current priorities are on the optimization engine improvements.

**Comment by FI00ds** [comment]
I can pick this up while waiting for the go ahead for i18n

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/570
