### ISSUE TITLE
[Bug] Optimizer Shows Incorrect Stats

### ISSUE THREAD

**Issue by yeanshu** [fribbels/hsr-optimizer#447]
## Description
Characters without no Planar Ornaments equipped have incorrect stats in Optimizer tab, this in turn results in incorrect damage calculations. 

If either Sphere or Rope is equipped, stats are correct. However, equipping relic sets makes no difference.

## Steps to Reproduce

1. Start optimizer for any character with no relics equipped
2. The top/current row in the results table has incorrect stats.

## Expected Behavior
Optimizer tab should show stats consistent with those in game, and with the Characters tab.

## Actual Behavior
Optimizer tab shows incorrect stats. Testing with other characters, the displayed ATK stat is overstated by roughly 12% of the base ATK. As seen below, Ratio's ATK is shown as 1827, when it actually is 1670, a difference of 157. The base ATK of Ratio/Cruising in the Stellar Sea is 1305, and 12% of that is also 157.

## Screenshots

Optimizer Tab with no relics
![image](https://github.com/fribbels/hsr-optimizer/assets/74160158/758e4309-b4f2-4d19-a231-7f55f440a3ac)

Character Tab with no relics
![image](https://github.com/fribbels/hsr-optimizer/assets/74160158/169e3cd3-0851-4dd6-81bb-7ddeeccd71e6)

In game with no relics
![image](https://github.com/fribbels/hsr-optimizer/assets/74160158/d22aaa1d-086a-4507-8aef-f58642066b88)

Optimizer Tab with Sphere equipped
![image](https://github.com/fribbels/hsr-optimizer/assets/74160158/6480c9e1-bfb3-41da-b7ee-e11fea0d50e9)

**Comment by fribbels** [comment]
@yeanshu Thanks for the bug report! The fix has been deployed now in https://github.com/fribbels/hsr-optimizer/pull/448
