### ISSUE TITLE
[Feature] Open character's scoring algorithm card after clicking on their icon in the relic insights panel

### ISSUE THREAD

**Issue by FI00ds** [fribbels/hsr-optimizer#478]
### Motivation

When I hover over the character I can see which substats an additional roll would ideally be allocated to.
However I don't have any quick way of seeing how much better the ideal case is than the next best case.

### Goal

When the user clicks on the character icon, open the ScoringModal and set scoringAlgorithmFocusCharacter to the clicked character

this can probably be kept to just the buckets view since the top 10 view both shows the spread and also lacks a natural clicking point

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/570
