### ISSUE TITLE
[Bug] Custom characters relic insights doesn't update

### ISSUE THREAD

**Issue by FI00ds** [fribbels/hsr-optimizer#479]
## Current Behaviour

1. View custom character view of relic insights panel
2. Remove one of the visible characters from the custom character selection
3. Character will still be displayed
4. Switch to all character view and back to custom character view
5. Character will no longer be displayed

## Expected Behavior

Would expect character to be removed from the display without having to cycle views

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/570
