### ISSUE TITLE
UX: Labels for filters after selection is made

### ISSUE THREAD

**Issue by cnojima** [fribbels/hsr-optimizer#49]
In the Optimizer, setting filters for set/planar/main-stat relics removes the prompt-text from view.

As different slots can use the same main stat, the filter card becomes visually confusing:
<img width="239" alt="Screenshot 2024-01-19 at 10 28 14 PM" src="https://github.com/fribbels/hsr-optimizer/assets/1007724/88601291-ca9a-45e7-b72a-1922a9f86a1b">

The filters should have some indicator after selection(s) are made:
- icon in selection
- floating label

**Comment by fribbels** [comment]
Resolving this one, added an icon for the pieces

![image](https://github.com/fribbels/hsr-optimizer/assets/7908525/5fd7be69-462e-44f3-bab3-bdad74e02229)
