### ISSUE TITLE
[Feature] Relic substats input validator

### ISSUE THREAD

**Issue by ronaldpereira** [fribbels/hsr-optimizer#51]
Currently the optimizer doesn't validate the substats that the user manually inputs to check if is valid. This could lead to users making some input mistakes.

Goal: Implement a simple roll validation algorithm to check if the substats for the relics are correct.

**Comment by ronaldpereira** [comment]
These are the substats rolls we can use for reference:

![image](https://github.com/fribbels/hsr-optimizer/assets/12674637/388ff476-36fc-4066-b128-29d902cf4fa3)

**Comment by fribbels** [comment]
I believe this can be considered done with the substat upgrades buttons

![Image](https://github.com/fribbels/hsr-optimizer/assets/7908525/e67d184f-151e-4cda-8f39-00263a4348fd)
