### ISSUE TITLE
[Feature] add uid to scorer url

### ISSUE THREAD

**Issue by FI00ds** [fribbels/hsr-optimizer#529]
### Motivation
currently if I want to share my character showcase, I have to either take 8 screenshots, send the url and uid separately, or I need to use a different website (e.g. enka)

### Goal
add a uid parameter to the url for the relicscorer to allow easy sharing of character showcase
have the relicscorer tab automatically load the showcase for the uid given in the url on load

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/570
