### ISSUE TITLE
Maintain selection after editing a relic in relics grid

### ISSUE THREAD

**Issue by FichteFoll** [fribbels/hsr-optimizer#540]
# Issue Template

## Description

After submitting an edit to a relic, it is visually unselected in the grid despite the graph and the stat view below still indicating the relic being selected. This can easily cause you to lose track of the relic when you want to look at what the

## Steps to Reproduce

1. Open relics grid
2. Select a relic
3. Edit a relic and submit

## Expected Behavior

Selection in the grid is maintained.

## Actual Behavior
Selection in the grid is lost.

## Additional Information

Since my primary intention was to see the updated char potential percentages (and also relative to to the other relics in order to compare which relic to improve next) while upgrading, it would also be nice if that could be updated without closing the modal.

**Comment by fribbels** [comment]
Released in https://github.com/fribbels/hsr-optimizer/pull/570
