### ISSUE TITLE
On the relic grid, open the scoring algorithm with the currently selected character

### ISSUE THREAD

**Issue by FichteFoll** [fribbels/hsr-optimizer#541]
# Issue Template

## Description
When opening the scoring algorithm modal, the "relic recommendation character" should be selected.

## Steps to Reproduce

1. Select a main character for recommendations
2. Click on "Scoring algorithm"

## Expected Behavior
The scoring algorithm/weights for the previously selected main character are shown.

## Actual Behavior
No scoring weights are shown.

## Additional Information

Similarly, when a new character is selected as the main character for recommendations, the scoring algorithm should open for this character by default and not for the previously selected one.

It probably does still make sense to keep the selection when you want to edit the weights for a "custom potential character", close the modal and then want to edit it again without also changing the main character inbetween, but that's less of a priority imo.

**Comment by FI00ds** [comment]
already fixed on the beta page with the exception of this:
> It probably does still make sense to keep the selection when you want to edit the weights for a "custom potential character", close the modal and then want to edit it again without also changing the main character inbetween, but that's less of a priority imo.
