### ISSUE TITLE
[Feature] Single-relic OCR tool for importing

### ISSUE THREAD

**Issue by fribbels** [fribbels/hsr-optimizer#57]
### Motivation

Current we only have the Full-account import (takes a while), and the relic scorer import (limited to 24 characters, have to manually assign relics to characters)

### Objective

Build an OCR tool on the optimizer site where users can paste their clipboard screenshot of a relic and have it OCR'd and imported. 

Other thoughts: there's two different relic displays, handle both? 

![Image](https://github.com/fribbels/hsr-optimizer/assets/7908525/fdf4dc74-b01a-40e2-8601-ba702189b3c7)

![Image](https://github.com/fribbels/hsr-optimizer/assets/7908525/ccc44ea8-a32f-4193-b5c7-a6520063b9dc)

**Comment by ronaldpereira** [comment]
Having some problems with number of substats for 3*, 4* and 5* differences. For 5* the OCR is working, but not for lower rarities. Will think a way to fix it in the future.

**Comment by fribbels** [comment]
Deprioritizing this one a bit, Reliquary and the relic modal changes have made this less important
