### ISSUE TITLE
[Feature]: Relic Grid filter UNEQUIPPED relics

### ISSUE THREAD

**Issue by cnojima** [fribbels/hsr-optimizer#59]
# Issue Template

## Description
When finding/sorting relics, I would like to be able to filter-out equipped relics.

## Expected Behavior
Filter checkbox/switch on UI to filter out equipped relics.  Maybe enable the inverse as well.  Since this infers a non-binary state, a dropdown with 3 options:
1. All
2. Equipped
3. Unequipped

## Actual Behavior
Best-case, sort by Character to float unequipped to the top.

**Comment by fribbels** [comment]
Maybe there's some better assets but here's the equipped/unequipped button icons I used for the e7 optimizer

![Image](https://github.com/fribbels/hsr-optimizer/assets/7908525/691ce148-a853-4dc4-99e9-ff13219a0bcc)
![Image](https://github.com/fribbels/hsr-optimizer/assets/7908525/03568bad-410c-47f1-ae35-cdc4602de4c3)
![Image](https://github.com/fribbels/hsr-optimizer/assets/7908525/c0d8e2aa-0680-428a-b9ae-99d7b1132212)
