### ISSUE TITLE
[Feature] Add Prompt-text to "Relic & stat" Filter input fields

### ISSUE THREAD

**Issue by cnojima** [fribbels/hsr-optimizer#61]
Current input fields are empty and a bit intimidating for new / casual / novice users:
![Image](https://github.com/fribbels/hsr-optimizer/assets/1007724/30bb1acb-869a-48d8-8192-ae98ead0cd4e)

Ask is to prepopulate the input fields with prompt text to suggest acceptable values.

**Comment by fribbels** [comment]
Resolving, updated the text headers for better instructions and hid the advanced options that most users won't need.
