### ISSUE TITLE
Formatting issue with screenshots

### ISSUE THREAD

**Issue by Goombario** [fribbels/hsr-optimizer#93]
# Issue Template

## Description
Using Firefox, when I download the screenshot the formatting for substats is broken. Please see the screenshots. Cleared cache, didn't fix. Tried on google chrome with the same data and it worked fine, so looks like it might have to do with the browser.

## Steps to Reproduce

1. Open the optimizer on Firefox
2. Go to characters
3. Click on the download button next to the "copy screenshot button"

## Expected Behavior
Screenshot downloads and the formatting is correct

## Actual Behavior
Screenshot downloads but the substat formatting is incorrect

## Screenshots
![Pela_2024-02-08_10-55-39](https://github.com/fribbels/hsr-optimizer/assets/12705535/0dbe49d5-a0f4-4b9e-a102-850d91b54807)
![Topaz   Numby_2024-02-08_10-54-29](https://github.com/fribbels/hsr-optimizer/assets/12705535/f5eb4777-6ac4-4ab9-8079-5dbb881f637f)
[fribbels-optimizer-save(1).json](https://github.com/fribbels/hsr-optimizer/files/14211583/fribbels-optimizer-save.1.json)

## Additional Information
Tried it on different screen resolutions as well but had no effect.

**Comment by fribbels** [comment]
Omg that looks awful - thanks for letting me know

**Comment by fribbels** [comment]
This issue should be resolved now - was a zoom scaling issue on firefox
